linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goerr113
        - containedctx
        - goconst
        - maintidx
    - path: "internal\\/server\\/.+\\.go"
      linters:
        - dupl
    - path: "internal\\/configuration\\/settings\\/.+\\.go"
      linters:
        - dupl
    - text: "^mnd: Magic number: 0[0-9]{3}, in <argument> detected$"
      source: "^.+= os\\.OpenFile\\(.+, .+, 0[0-9]{3}\\)"
      linters:
        - gomnd
    - text: "^mnd: Magic number: 0[0-9]{3}, in <argument> detected$"
      source: "^.+= os\\.MkdirAll\\(.+, 0[0-9]{3}\\)"
      linters:
        - gomnd
    - linters:
        - lll
      source: "^//go:generate .+$"
    - text: "returns interface \\(github\\.com\\/vishvananda\\/netlink\\.Link\\)"
      linters:
        - ireturn
    - path: "internal\\/openvpn\\/pkcs8\\/descbc\\.go"
      text: "newCipherDESCBCBlock returns interface \\(github\\.com\\/youmark\\/pkcs8\\.Cipher\\)"
      linters:
        - ireturn
    - path: "internal\\/firewall\\/.*\\.go"
      text: "string `-i ` has [1-9][0-9]* occurrences, make it a constant"
      linters:
        - goconst
    - path: "internal\\/provider\\/ipvanish\\/updater\\/servers.go"
      text: "string ` in ` has 3 occurrences, make it a constant"
      linters:
        - goconst
    - path: "internal\\/vpn\\/portforward.go"
      text: 'directive `//nolint:ireturn` is unused for linter "ireturn"'
      linters:
        - nolintlint

linters:
  enable:
    # - cyclop
    # - errorlint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint

run:
  skip-dirs:
    - .devcontainer
    - .github
    - doc
